#!/bin/sh

case $* in
	--help)
		echo "Someday I will help you.  I promise!"
		;;

	"")
		echo "I am currently good at doing nothing."
		;;

	*)
		echo "I am sorry I just don't know how to $*.  Maybe someday."
		;;
esac
