"use strict";

const dummyUsers = [
  {
    "username": "proxy",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.078946,
    "created-at": 1436221971.078946,
    "group": 62,
    "builtin": true,
    "full_name": "Packet Filter pseudo-user",
    "logged-in": false,
    "id": 62,
    "home": "/nonexistent",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "_pflogd",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.085953,
    "created-at": 1436221971.085953,
    "group": 64,
    "builtin": true,
    "full_name": "pflogd privsep user",
    "logged-in": false,
    "id": 64,
    "home": "/var/empty",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "_dhcp",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.087667,
    "created-at": 1436221971.087667,
    "group": 65,
    "builtin": true,
    "full_name": "dhcp programs",
    "logged-in": false,
    "id": 65,
    "home": "/var/empty",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "uucp",
    "sshpubkey": null,
    "shell": "/usr/local/libexec/uucp/uucico",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.089358,
    "created-at": 1436221971.089358,
    "group": 66,
    "builtin": true,
    "full_name": "UUCP pseudo-user",
    "logged-in": false,
    "id": 66,
    "home": "/var/spool/uucppublic",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "pop",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.091019,
    "created-at": 1436221971.091019,
    "group": 6,
    "builtin": true,
    "full_name": "Post Office Owner",
    "logged-in": false,
    "id": 68,
    "home": "/nonexistent",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "www",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.092668,
    "created-at": 1436221971.092668,
    "group": 80,
    "builtin": true,
    "full_name": "World Wide Web Owner",
    "logged-in": false,
    "id": 80,
    "home": "/nonexistent",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "smmsp",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.094304,
    "created-at": 1436221971.094304,
    "group": 25,
    "builtin": true,
    "full_name": "Sendmail Submission User",
    "logged-in": false,
    "id": 25,
    "home": "/var/spool/clientmqueue",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "mailnull",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.09595,
    "created-at": 1436221971.09595,
    "group": 26,
    "builtin": true,
    "full_name": "Sendmail Default User",
    "logged-in": false,
    "id": 26,
    "home": "/var/spool/mqueue",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "sshd",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.097642,
    "created-at": 1436221971.097642,
    "group": 22,
    "builtin": true,
    "full_name": "Secure Shell Daemon",
    "logged-in": false,
    "id": 22,
    "home": "/var/empty",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "daemon",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.0993,
    "created-at": 1436221971.0993,
    "group": 1,
    "builtin": true,
    "full_name": "Owner of many system processes",
    "logged-in": false,
    "id": 1,
    "home": "/root",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "bin",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.102584,
    "created-at": 1436221971.102584,
    "group": 7,
    "builtin": true,
    "full_name": "Binaries Commands and Source",
    "logged-in": false,
    "id": 3,
    "home": "/",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "operator",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.104225,
    "created-at": 1436221971.104225,
    "group": 5,
    "builtin": true,
    "full_name": "System &",
    "logged-in": false,
    "id": 2,
    "home": "/",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "kmem",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.105876,
    "created-at": 1436221971.105876,
    "group": 2,
    "builtin": true,
    "full_name": "KMem Sandbox",
    "logged-in": false,
    "id": 5,
    "home": "/",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "tty",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.107519,
    "created-at": 1436221971.107519,
    "group": 65533,
    "builtin": true,
    "full_name": "Tty Sandbox",
    "logged-in": false,
    "id": 4,
    "home": "/",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "nullmail",
    "sshpubkey": null,
    "shell": "/bin/sh",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.109153,
    "created-at": 1436221971.109153,
    "group": 522,
    "builtin": true,
    "full_name": "Nullmailer Mail System",
    "logged-in": false,
    "id": 522,
    "home": "/var/spool/nullmailer",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "man",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.110804,
    "created-at": 1436221971.110804,
    "group": 9,
    "builtin": true,
    "full_name": "Mister Man Pages",
    "logged-in": false,
    "id": 9,
    "home": "/usr/share/man",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "news",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.112617,
    "created-at": 1436221971.112617,
    "group": 8,
    "builtin": true,
    "full_name": "News Subsystem",
    "logged-in": false,
    "id": 8,
    "home": "/",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "games",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.114305,
    "created-at": 1436221971.114305,
    "group": 13,
    "builtin": true,
    "full_name": "Games pseudo-user",
    "logged-in": false,
    "id": 7,
    "home": "/",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "auditdistd",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.115957,
    "created-at": 1436221971.115957,
    "group": 77,
    "builtin": true,
    "full_name": "Auditdistd unprivileged user",
    "logged-in": false,
    "id": 78,
    "home": "/var/empty",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "ftp",
    "sshpubkey": null,
    "shell": "/bin/csh",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.117601,
    "created-at": 1436221971.117601,
    "group": 14,
    "builtin": true,
    "full_name": null,
    "logged-in": false,
    "id": 14,
    "home": "/nonexistent",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "bind",
    "sshpubkey": null,
    "shell": "/usr/sbin/nologin",
    "locked": false,
    "groups": [],
    "sessions": [],
    "updated-at": 1436221971.119238,
    "created-at": 1436221971.119238,
    "group": 53,
    "builtin": true,
    "full_name": "Bind Sandbox",
    "logged-in": false,
    "id": 53,
    "home": "/",
    "sudo": false,
    "email": null,
    "password_disabled": false
  },
  {
    "username": "root",
    "sshpubkey": null,
    "shell": "/bin/csh",
    "locked": false,
    "builtin": true,
    "sessions": [
      {
        "username": "root",
        "resource": null,
        "id": 2,
        "updated-at": 1436222477.102969,
        "created-at": 1436222477.102969,
        "port": 35057,
        "address": "127.0.0.1",
        "active": true,
        "started-at": 1436222477.098721
      },
      {
        "username": "root",
        "resource": null,
        "id": 53,
        "updated-at": 1436295829.782153,
        "created-at": 1436295829.782153,
        "port": 57071,
        "address": "10.5.0.176",
        "active": true,
        "started-at": 1436295829.778141
      },
      {
        "username": "root",
        "resource": null,
        "id": 56,
        "updated-at": 1436297667.10981,
        "created-at": 1436297667.10981,
        "port": 49666,
        "address": "127.0.0.1",
        "active": true,
        "started-at": 1436297667.104117
      },
      {
        "username": "root",
        "resource": null,
        "id": 79,
        "updated-at": 1436920779.428362,
        "created-at": 1436920779.428362,
        "port": 50844,
        "address": "10.5.0.176",
        "active": true,
        "started-at": 1436920779.423464
      },
      {
        "username": "root",
        "resource": null,
        "id": 80,
        "updated-at": 1436924641.307074,
        "created-at": 1436924641.307074,
        "port": 52328,
        "address": "10.5.0.176",
        "active": true,
        "started-at": 1436924641.302213
      }
    ],
    "sudo": false,
    "created-at": 1436221971.100949,
    "group": 0,
    "updated-at": 1436221971.100949,
    "full_name": "root",
    "logged-in": true,
    "id": 0,
    "home": "/root",
    "groups": [],
    "email": null,
    "password_disabled": false
  }
];

export default dummyUsers;