"use strict";
var ServiceFtpTlsoptionsItems = {
    ALLOW_CLIENT_RENEGOTIATIONS: 'ALLOW_CLIENT_RENEGOTIATIONS',
    ALLOW_DOT_LOGIN: 'ALLOW_DOT_LOGIN',
    ALLOW_PER_USER: 'ALLOW_PER_USER',
    COMMON_NAME_REQUIRED: 'COMMON_NAME_REQUIRED',
    ENABLE_DIAGNOSTICS: 'ENABLE_DIAGNOSTICS',
    EXPORT_CERTIFICATE_DATA: 'EXPORT_CERTIFICATE_DATA',
    NO_CERTIFICATE_REQUEST: 'NO_CERTIFICATE_REQUEST',
    NO_EMPTY_FRAGMENTS: 'NO_EMPTY_FRAGMENTS',
    NO_SESSION_REUSE_REQUIRED: 'NO_SESSION_REUSE_REQUIRED',
    STANDARD_ENV_VARS: 'STANDARD_ENV_VARS',
    DNS_NAME_REQUIRED: 'DNS_NAME_REQUIRED',
    IP_ADDRESS_REQUIRED: 'IP_ADDRESS_REQUIRED'
};
exports.ServiceFtpTlsoptionsItems = ServiceFtpTlsoptionsItems;
